covid19_self_assessment.covid19_self_assessment_type.*:
  type: config_entity
  label: 'Covid19 self assessment type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
